### ISSUE TITLE
JunctionQC not defined in example config

### ISSUE THREAD

**Issue by yfarjoun** [RajLabMSSM/leafcutter-pipeline#5]
Hello,

Thanks for making this pipeline available. I'm trying to use it, but running into trouble when attempting to run the example provided. The Snakefile references a certain  `config["junctionQC"]` which doesn't seem to be present in the `example/config.yaml`. 

Could you clarify what needs to be put here? 

Thanks!

**Comment by jackhump** [comment]
Thanks for catching this. Try adding
 junctionQC: False
to your config.yaml

The junction QC script is a little buggy so you can skip for most applications.

**Comment by yfarjoun** [comment]
Thanks! I'll submit a PR as well.
